# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('notes', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='NutRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(choices=[('1', 'fiber'), ('2', 'sodium'), ('3', 'sugar')], default='', max_length=100)),
                ('nutritional_field', models.CharField(choices=[('1', 'category'), ('2', 'ingredients'), ('3', 'name'), ('4', 'sodium'), ('5', 'sugar')], default='', max_length=100)),
                ('rule_type', models.CharField(choices=[('1', 'contains'), ('2', 'first_item'), ('3', 'lte')], default='', max_length=100)),
                ('value', models.FloatField()),
                ('wellness', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('food_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.FoodCat')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_items', models.IntegerField()),
                ('scan_ts', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(default='android', max_length=15)),
                ('user_id', models.CharField(default='keyser_soze', max_length=15)),
                ('food_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.FoodCat')),
            ],
            options={
                'ordering': ('scan_ts',),
            },
        ),
        migrations.CreateModel(
            name='UPCCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc_code', models.TextField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UPCDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrix_id', models.TextField(max_length=30)),
                ('item_name', models.TextField(max_length=100)),
                ('brand_id', models.TextField(max_length=30)),
                ('brand_name', models.TextField(max_length=100)),
                ('item_description', models.TextField(max_length=500)),
                ('api_last_update', models.DateTimeField()),
                ('ingredients', models.TextField(max_length=100)),
                ('calories', models.FloatField()),
                ('calories_from_fat', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('total_carb', models.FloatField()),
                ('dietary_fiber', models.FloatField()),
                ('sugars', models.FloatField()),
                ('protein', models.FloatField()),
                ('vitamin_a_dv', models.FloatField()),
                ('vitamin_c_dv', models.FloatField()),
                ('calcium_dv', models.FloatField()),
                ('iron_dv', models.FloatField()),
                ('serving_per_cont', models.FloatField()),
                ('serving_size_qty', models.FloatField()),
                ('serving_size_unit', models.TextField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UPCCode')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='WellScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellness', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.NutRule')),
                ('upc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UPCCode')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='scan',
            name='upc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UPCCode'),
        ),
    ]
