# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20160723_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='upc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upc', to='restapi.UPCCode'),
        ),
    ]
