# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20160723_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc_code', models.TextField(max_length=50)),
                ('item_name', models.TextField(max_length=100)),
                ('brand_id', models.TextField(max_length=30)),
                ('brand_name', models.TextField(max_length=100)),
                ('item_image', models.TextField()),
                ('item_description', models.TextField(max_length=500)),
                ('api_last_update', models.DateTimeField()),
                ('ingredients', models.TextField(max_length=100)),
                ('calories', models.FloatField()),
                ('calories_from_fat', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('total_carb', models.FloatField()),
                ('dietary_fiber', models.FloatField()),
                ('sugars', models.FloatField()),
                ('protein', models.FloatField()),
                ('vitamin_a_dv', models.FloatField()),
                ('vitamin_c_dv', models.FloatField()),
                ('calcium_dv', models.FloatField()),
                ('iron_dv', models.FloatField()),
                ('serving_per_cont', models.FloatField()),
                ('serving_size_qty', models.FloatField()),
                ('serving_size_unit', models.TextField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='upcdetail',
            name='upc_id',
        ),
        migrations.AddField(
            model_name='foodcat',
            name='load_cat',
            field=models.TextField(default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='scan',
            name='upc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UPC'),
        ),
        migrations.AlterField(
            model_name='wellscore',
            name='upc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UPC'),
        ),
        migrations.DeleteModel(
            name='UPCCode',
        ),
        migrations.DeleteModel(
            name='UPCDetail',
        ),
    ]
