# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20160723_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrule',
            name='value',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
