# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20160723_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_status',
            field=models.TextField(default='Initial data load', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='upc_raw',
            field=models.TextField(default='9999', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upc',
            name='data_source',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scan',
            name='num_items',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='wellscore',
            name='wellness',
            field=models.NullBooleanField(default=False),
        ),
    ]
