# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_auto_20160725_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='upc_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.UPC'),
        ),
    ]
