# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_auto_20160725_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcat',
            name='abbr',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foodcat',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodcat',
            name='load_cat',
            field=models.TextField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='foodcat',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodcat',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nutrule',
            name='food_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.FoodCat'),
        ),
        migrations.AlterField(
            model_name='nutrule',
            name='nutrient',
            field=models.CharField(blank=True, choices=[('1', 'fiber'), ('2', 'sodium'), ('3', 'sugar')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutrule',
            name='nutritional_field',
            field=models.CharField(blank=True, choices=[('1', 'category'), ('2', 'ingredients'), ('3', 'name'), ('4', 'sodium'), ('5', 'sugar')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutrule',
            name='rule_type',
            field=models.CharField(blank=True, choices=[('1', 'contains'), ('2', 'first_item'), ('3', 'lte')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutrule',
            name='value',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nutrule',
            name='wellness',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scan',
            name='food_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.FoodCat'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='upc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.UPC'),
        ),
        migrations.AlterField(
            model_name='wellscore',
            name='nut_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.NutRule'),
        ),
    ]
